<%
rerun = File.file?('rerun.txt') ? IO.read('rerun.txt') : ""
rerun = rerun.strip.gsub /\s/, ' '
rerun_opts = rerun.empty? ? "--format #{ENV['CUCUMBER_FORMAT'] || 'progress'} -r features features/" : "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} -r features #{rerun}"
std_opts = "--format #{ENV['CUCUMBER_FORMAT'] || 'progress'} -r features features/"
%>
default: <%= std_opts %>
rerun: <%= rerun_opts %> --format rerun --out rerun.txt
